### ISSUE TITLE
Error: Cannot find module 'threads_a_gogo'

### ISSUE THREAD

**Issue by cebbec** [xk/node-threads-a-gogo#1]
Installation with npm ok (no error)

But when I try to launch an example, I have the <code>Cannot find module 'threads_a_gogo'</code> error.

I am on ubuntu 11.10

Here is what I have in my threads_a_gogo module directory:

``` bash
/usr/lib/node_modules/threads_a_gogo# ls
AUTHORS    build  examples  package.json  src   wscript
benchmark  deps   LICENSE   README.md     test
```

I should have an index.js or a threads_a_gogo.js file ?

**Comment by xkero** [comment]
Fixed it for me by changing `"main": "build/release/threads_a_gogo.node"` to `"main": "build/Release/threads_a_gogo.node"` in package.json (i.e. should be **R**elease instead of **r**elease). I'm assuming xk develops on Mac which uses a case-insensitive filesystem by default while those of us affected are using a case-sensitive filesystem.

**Comment by Moonant** [comment]
@xkero, That Great !
How could you find this ?!!

**Comment by luckscx** [comment]
xkero thanks~ it works
